"""Migration gates: schema state, drift, trigger behavior.

(The upgrade → downgrade → upgrade reversibility cycle already ran inside the
session ``database`` fixture — reaching these tests proves it.)
"""

import pytest
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

from tests.db import DatabaseInfo

pytestmark = [pytest.mark.integration, pytest.mark.anyio]


class TestSchemaState:
    async def test_vector_extension_installed(self, owner_engine: AsyncEngine) -> None:
        async with owner_engine.connect() as conn:
            result = await conn.execute(
                text("SELECT count(*) FROM pg_extension WHERE extname = 'vector'")
            )
            assert result.scalar_one() == 1

    async def test_runtime_roles_exist_without_bypassrls(self, owner_engine: AsyncEngine) -> None:
        async with owner_engine.connect() as conn:
            result = await conn.execute(
                text(
                    "SELECT rolname, rolbypassrls, rolsuper FROM pg_roles "
                    "WHERE rolname IN ('cg_app', 'cg_worker')"
                )
            )
            rows = {row[0]: (row[1], row[2]) for row in result.fetchall()}
        assert set(rows) == {"cg_app", "cg_worker"}
        for role, (bypassrls, superuser) in rows.items():
            assert not bypassrls, f"{role} must never have BYPASSRLS"
            assert not superuser, f"{role} must never be superuser"

    async def test_rls_enabled_on_organizations(self, owner_engine: AsyncEngine) -> None:
        async with owner_engine.connect() as conn:
            result = await conn.execute(
                text("SELECT relrowsecurity FROM pg_class WHERE relname = 'organizations'")
            )
            assert result.scalar_one() is True

    async def test_app_current_tenant_is_null_without_context(
        self, owner_engine: AsyncEngine
    ) -> None:
        async with owner_engine.connect() as conn:
            result = await conn.execute(text("SELECT app_current_tenant()"))
            assert result.scalar_one() is None


class TestUpdatedAtTrigger:
    async def test_updated_at_advances_on_update(self, owner_engine: AsyncEngine) -> None:
        async with owner_engine.begin() as conn:
            row = (
                await conn.execute(
                    text(
                        "INSERT INTO jobs (kind, status, attempts, max_attempts) "
                        "VALUES ('ingest', 'queued', 0, 3) RETURNING id, updated_at"
                    )
                )
            ).one()
            await conn.execute(text("SELECT pg_sleep(0.05)"))
            updated = (
                await conn.execute(
                    text("UPDATE jobs SET status = 'running' WHERE id = :id RETURNING updated_at"),
                    {"id": row.id},
                )
            ).scalar_one()
            assert updated > row.updated_at
            await conn.execute(text("DELETE FROM jobs WHERE id = :id"), {"id": row.id})


class TestModelDrift:
    def test_models_match_migrations(self, database: DatabaseInfo) -> None:
        """`alembic check` — a model change without a migration fails CI here."""
        from alembic import command
        from alembic.config import Config

        cfg = Config("alembic.ini")
        cfg.set_main_option("sqlalchemy.url", database.owner_url)
        command.check(cfg)  # raises AutogenerateDiffsDetected on drift
